### PR TITLE
Remove newPage

### PR DESCRIPTION
**Pull request by bjexe**
it wasn't cool after all...

### CODE REVIEW

**Review by ZetaRho — COMMENTED** [review]
this removes the index page, will close comment and await new pull affecting the newPage

**Comment by ZetaRho** [comment]
closing pull

**Comment by bjexe** [comment]
Removed the correct file

**Review by ZetaRho — COMMENTED** [review]
looks good, thanks for the fix, will approve the merge

**Review by ZetaRho — APPROVED** [review]
approved

**Pull request merged**
